# Generated by Django 5.0.6 on 2024-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(blank=True, choices=[('function', 'function'), ('Science Fiction', 'Science Fiction'), ('function', 'function'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Mystery', 'Mystery')], max_length=30, null=True),
        ),
    ]
