# Generated by Django 5.0.6 on 2024-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.CharField(default='2000', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
