# Generated by Django 5.0.6 on 2024-05-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_books_booklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='tittle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
