# Generated by Django 5.0.6 on 2024-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_books_author_alter_books_booklink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
