# Generated by Django 5.0.6 on 2024-05-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_books_author_alter_books_booklink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='booklink',
            field=models.ImageField(null=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('function', 'function'), ('Science Fiction', 'Science Fiction'), ('function', 'function'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Mystery', 'Mystery')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='des',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='lan',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='numofpage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='tittle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
