# Generated by Django 5.0.6 on 2024-05-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_books_booklink_alter_books_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='booklink',
            new_name='book_link',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='lan',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='books',
            name='numofpage',
        ),
        migrations.AddField(
            model_name='books',
            name='num_of_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('function', 'Function'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Mystery', 'Mystery')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
