# Generated by Django 5.0.6 on 2024-05-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_booklink_books_book_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='tittle',
        ),
    ]
