# Generated by Django 5.0.6 on 2024-05-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_rename_title_books_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
