# Generated by Django 5.0.6 on 2024-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
