# Generated by Django 5.0.6 on 2024-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(default='0', max_length=7, null=True),
        ),
    ]
