# Generated by Django 5.0.6 on 2024-05-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_books_tittle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photo')),
            ],
            options={
                'verbose_name': 'books',
            },
        ),
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
    ]
